#!/usr/bin/env python3
"""Convert art/spritesheet.png (1024x640, 4x pixel art) into src/sprites.h (RGB565).

Each 4x4 block is majority-voted down to one logical pixel, snapped to the game
palette, and sliced along the 8x5 grid of 32px cells. Magenta is the transparency
key (0xF81F in RGB565).
"""
from PIL import Image
from collections import Counter
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'spritesheet.png')
OUT = os.path.join(HERE, '..', 'src', 'sprites.h')

PALETTE = [
    (0xFF, 0x00, 0xFF),  # KEY (transparent) — must be index 0
    (0x28, 0x24, 0x1E), (0x2E, 0x34, 0x58), (0x1E, 0x22, 0x3C), (0xF4, 0xC8, 0xA0),
    (0xD8, 0x38, 0x30), (0xFF, 0xFF, 0xFF), (0x6E, 0xBA, 0x46), (0x46, 0x82, 0x28),
    (0xC8, 0x3C, 0x32), (0x8C, 0x22, 0x1E), (0xB0, 0xB4, 0xBE), (0x6E, 0x72, 0x7E),
    (0x96, 0x76, 0x54), (0x68, 0x4E, 0x34), (0xFF, 0xD2, 0x3C), (0xBE, 0x8C, 0x14),
    (0xEB, 0x3C, 0x46),
]

def nearest(px):
    r, g, b = px[:3]
    best, bd = 0, 1 << 30
    for i, (pr, pg, pb) in enumerate(PALETTE):
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if d < bd:
            bd, best = d, i
    return best

def c565(rgb):
    r, g, b = rgb
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

img = Image.open(SRC).convert('RGB')
assert img.size == (1024, 640), f'unexpected size {img.size}'
W, H = 256, 160
logical = [[0] * W for _ in range(H)]
pix = img.load()
for y in range(H):
    for x in range(W):
        votes = Counter()
        for dy in range(4):
            for dx in range(4):
                votes[nearest(pix[x * 4 + dx, y * 4 + dy])] += 1
        logical[y][x] = votes.most_common(1)[0][0]

# name: (col, row, span_cols)
CELLS = {
    'ninja_run_a': (0, 0, 1), 'ninja_run_b': (1, 0, 1), 'ninja_leap': (2, 0, 1),
    'ninja_windup': (3, 0, 1), 'ninja_swing': (4, 0, 1), 'ninja_hurt': (5, 0, 1),
    'ninja_dead': (6, 0, 1),
    'demon_a': (0, 1, 1), 'demon_b': (1, 1, 1),
    'rock_a': (2, 1, 1), 'rock_b': (3, 1, 1), 'rock_c': (4, 1, 1),
    'bamboo': (0, 2, 3), 'spikes': (3, 2, 3),
    'tree_a': (0, 3, 1), 'tree_b': (1, 3, 1), 'torii': (2, 3, 1), 'lantern': (3, 3, 1),
    'coin_a': (0, 4, 1), 'coin_b': (1, 4, 1), 'coin_c': (2, 4, 1), 'coin_d': (3, 4, 1),
    'heart_full': (4, 4, 1), 'heart_empty': (5, 4, 1),
    'fx_slash': (6, 4, 1), 'fx_poof': (7, 4, 1),
}

lines = [
    '// Generated by art/mksprites.py from art/spritesheet.png — do not edit by hand.',
    '#pragma once',
    '#include <stdint.h>',
    '',
    'constexpr uint16_t SPR_KEY = 0xF81F;   // magenta = transparent',
    'struct SpriteImg { const uint16_t *data; uint8_t w, h; };',
    '',
]

total = 0
for name, (col, row, span) in CELLS.items():
    x0, y0 = col * 32, row * 32
    w, h = span * 32, 32
    # trim to content
    minx, miny, maxx, maxy = w, h, -1, -1
    for yy in range(h):
        for xx in range(w):
            if logical[y0 + yy][x0 + xx] != 0:
                minx = min(minx, xx); maxx = max(maxx, xx)
                miny = min(miny, yy); maxy = max(maxy, yy)
    if maxx < 0:
        raise SystemExit(f'{name}: cell is empty!')
    tw, th = maxx - minx + 1, maxy - miny + 1
    vals = []
    for yy in range(miny, maxy + 1):
        for xx in range(minx, maxx + 1):
            idx = logical[y0 + yy][x0 + xx]
            vals.append(0xF81F if idx == 0 else c565(PALETTE[idx]))
    total += len(vals) * 2
    body = ',\n  '.join(
        ','.join(f'0x{v:04X}' for v in vals[i:i + 16]) for i in range(0, len(vals), 16))
    lines.append(f'static const uint16_t spr_{name}_px[] = {{\n  {body}\n}};')
    lines.append(f'constexpr SpriteImg SPR_{name.upper()} = {{ spr_{name}_px, {tw}, {th} }};')
    lines.append('')
    print(f'{name:14s} {tw:3d}x{th:2d}')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines))
print(f'\nwrote {OUT} ({total} bytes of pixel data)')
